### ISSUE TITLE
Pass component as message

### ISSUE THREAD

**Issue by alfonsozunigaj** [JuzSer/vue-bot-ui#17]
Would it be possible to create a new type of message that embeds a component pass to it through the parameters instead of getting the text to be displayed?

**Comment by juzser** [comment]
You can check in README section [#component](https://github.com/juzser/vue-bot-ui#components) for more information. 

If there is not component you are finding, feel free to let me know or create  new component yourself via the path `components/MessageBubble/..` and then create PR, I will review and merge.
