### ISSUE TITLE
Need some update.

### ISSUE THREAD

**Issue by mostafijartisan** [JuzSer/vue-bot-ui#25]
1. add minimize, maximize and close button on top.
2. we can customize BubbleIcon & CloseIcon icon.
3. header slot not working.
4. Single button option (bot and user both side)

**Comment by juzser** [comment]
Hi there, 
Thanks for your feedbacks, but currently I cannot update this package cuz of less time. 
If you can create a pull request, so I'm happy to review and merge it. Or you have to wait for a long time. 

Cheers.
