### ISSUE TITLE
How to connect VueBotUI to Azure Bot

### ISSUE THREAD

**Issue by VuEMAX** [JuzSer/vue-bot-ui#35]
Hi. I would like to know how to connect VueBotUI to Azure Bot. Thanks

**Comment by andersenmp** [comment]
Hi,

A simple integration is to create your message service to call your azure bot instead of the fake messages.

My quick solution is:

Create your service azure-bot:


```javascript
import axios from 'axios'

export const messageService = {
  getBotMessage
}

async function getBotMessage (value) {
  const headers = {
    'Content-Type': 'application/json',
    'Ocp-Apim-Subscription-Key': '{Subscription-Key-Here}'
  }

  const response = await axios
    .post('https://{region}.api.cognitive.microsoft.com/language/:query-knowledgebases?projectName={PROJECT_NAME_HERE}&api-version=2021-10-01&deploymentName=production', {
      'question': value
    }, {
      headers: headers
    })

  return response.data.answers[0].answer
}

```



Import your new services

`import { messageService } from './helpers/azure-bot'`


Change your getResponse function. I prefer to work with async instead of promises 


```javascript
    // Submit the message from user to bot API, then get the response from Bot
    async getResponse (value) {
      // Loading
      this.botTyping = true

      const response = await messageService.getBotMessage(value)
      const replyMessage = {
        agent: 'bot',
        type: 'text',
        text: response
      }

      this.inputDisable = response.disableInput
      this.messageData.push(replyMessage)

      // finish
      this.botTyping = false
    }


```

**Comment by juzser** [comment]
Hi there, 

Actually, this package is just Bot UI, so you can integrate to any bot platform. The input is just a message array. 
You can follow @andersenmp , that's totally correct. 

But I've not updated the bot to lazy-load the messages or load more on scroll behavior; So be aware that your message data should be lazy-loaded or pass parts of data into it by timeout or somehow.
