### ISSUE TITLE
Can't close bubble button or hide it.

### ISSUE THREAD

**Issue by TheFunnyBear** [JuzSer/vue-bot-ui#64]
When i set  bubbleBtnSize: 0 in options and :is-open="true", i still can  toggle bot window with bubble icons. Bubble icons not hide and not change it size.

![Выделение_550](https://github.com/user-attachments/assets/fdac434b-9741-41e3-b05a-9f3f7588cd97)

![Выделение_549](https://github.com/user-attachments/assets/5e2c4daa-789b-4025-b38c-2a36cd258a46)

**Comment by juzser** [comment]
@TheFunnyBear You can inspect element and use CSS to hide it, I guess I had already put a specific css class to do that. 
Your case is specific base on your need, so I cannot update the lib as global change.

**Comment by TheFunnyBear** [comment]
Thanks, it worked for me.

<style>
.qkb-bubble-btn {
    display: none;
}
</style>
